version: '3.2'
services:
  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8083:8080
    environment:
      - KUBERNETES_NAMESPACE=jenkins-local
    volumes:
#      - /tmp/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ./jobs:/var/jenkins_home/jobs
#      - ~/.ssh/id_rsa:/var/jenkins_home/.ssh/id_rsa
